
string = input("enter string: ")
capitals = 0
# for i in range(ord("A"),ord("Z")):
#     capitals += string.count(chr(i))
capitals += string.count("A")
capitals += string.count("B")
capitals += string.count("C")
capitals += string.count("D")
capitals += string.count("E")
capitals += string.count("F")
capitals += string.count("G")
capitals += string.count("H")
capitals += string.count("I")
capitals += string.count("J")
capitals += string.count("K")
capitals += string.count("L")
capitals += string.count("M")
capitals += string.count("N")
capitals += string.count("O")
capitals += string.count("P")
capitals += string.count("Q")
capitals += string.count("R")
capitals += string.count("S")
capitals += string.count("T")
capitals += string.count("U")
capitals += string.count("V")
capitals += string.count("W")
capitals += string.count("X")
capitals += string.count("Y")
capitals += string.count("Z")
print(capitals)
